name: Build and Push Docker Images (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Image version'
        required: true
      oint_ru:
        type: string
        description: 'URL of OInt (ru)'
        required: true
      oint_en:
        type: string
        description: 'URL of OInt (en)'
        required: true
      melezh_ru:
        type: string
        description: 'URL of Melezh (ru)'
        required: true
      melezh_en:
        type: string
        description: 'URL of Melezh (en)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create build directory
        run: |
          mkdir -p /tmp/melezh-build/{en,ru}

      - name: Download DEB files from Draft Release (auth)
        run: |
          # English packages
          wget --header="Authorization: Bearer ${{ secrets.TOKEN }}" \
               -O /tmp/melezh-build/en/oint.deb \
               "${{ github.event.inputs.oint_en }}"
          wget --header="Authorization: Bearer ${{ secrets.TOKEN }}" \
               -O /tmp/melezh-build/en/melezh.deb \
               "${{ github.event.inputs.melezh_en }}"
          # Russian packages
          wget --header="Authorization: Bearer ${{ secrets.TOKEN }}" \
               -O /tmp/melezh-build/ru/oint.deb \
               "${{ github.event.inputs.oint_ru }}"
          wget --header="Authorization: Bearer ${{ secrets.TOKEN }}" \
               -O /tmp/melezh-build/ru/melezh.deb \
               "${{ github.event.inputs.melezh_ru }}"

      - name: Log in to GHCR
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push English image
        run: |
          cd ./service/docker/ghcr/en
          cp /tmp/melezh-build/en/oint.deb .
          cp /tmp/melezh-build/en/melezh.deb .
          docker build \
            -t ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-en .
          docker push ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-en

      - name: Build and Push Russian image
        run: |
          cd ./service/docker/ghcr/ru
          cp /tmp/melezh-build/ru/oint.deb .
          cp /tmp/melezh-build/ru/melezh.deb .
          docker build \
            -t ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-ru .
          docker push ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-ru
