name: Build and Push Docker Images (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Image version'
        required: true
      melezh_version:
        type: string
        description: 'Melezh version'
        required: true
      oint_version:
        type: string
        description: 'OInt version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create build directory
        run: |
          mkdir -p /tmp/melezh-build/{en,ru}

      - name: Download DEB files from Draft Release (auth)
        run: |
          # English packages (deb)
          wget -O /tmp/melezh-build/en/oint.deb \
               "https://api.athenaeum.digital/tc/job/Release/lastSuccessfulBuild/artifact/${{ github.event.inputs.oint_version }}/oint_${{ github.event.inputs.oint_version }}_all_en.deb"
          wget -O /tmp/melezh-build/en/melezh.deb \
               "https://api.athenaeum.digital/tc/job/Melezh_Release/lastSuccessfulBuild/artifact/${{ github.event.inputs.melezh_version }}/melezh_${{ github.event.inputs.melezh_version }}_all_en.deb"

          # Russian packages (deb)
          wget --header="Authorization: Bearer ${{ secrets.TOKEN }}" \
               -O /tmp/melezh-build/ru/oint.deb \
               "https://api.athenaeum.digital/tc/job/Release/lastSuccessfulBuild/artifact/${{ github.event.inputs.oint_version }}/oint_${{ github.event.inputs.oint_version }}_all_ru.deb"
          wget -O /tmp/melezh-build/ru/melezh.deb \
               "https://api.athenaeum.digital/tc/job/Melezh_Release/lastSuccessfulBuild/artifact/${{ github.event.inputs.melezh_version }}/melezh_${{ github.event.inputs.melezh_version }}_all_ru.deb"

          # English packages (rpm)
          wget -O /tmp/melezh-build/en/oint.rpm \
               "https://api.athenaeum.digital/tc/job/Release/lastSuccessfulBuild/artifact/${{ github.event.inputs.oint_version }}/oint-${{ github.event.inputs.oint_version }}-1.noarch_en.rpm"
          wget -O /tmp/melezh-build/en/melezh.rpm \
               "https://api.athenaeum.digital/tc/job/Melezh_Release/lastSuccessfulBuild/artifact/${{ github.event.inputs.melezh_version }}/melezh-${{ github.event.inputs.melezh_version }}-1.noarch_en.rpm"

          # Russian packages (rpm)
          wget --header="Authorization: Bearer ${{ secrets.TOKEN }}" \
               -O /tmp/melezh-build/ru/oint.rpm \
               "https://api.athenaeum.digital/tc/job/Release/lastSuccessfulBuild/artifact/${{ github.event.inputs.oint_version }}/oint-${{ github.event.inputs.oint_version }}-1.noarch_ru.rpm"
          wget -O /tmp/melezh-build/ru/melezh.rpm \
               "https://api.athenaeum.digital/tc/job/Melezh_Release/lastSuccessfulBuild/artifact/${{ github.event.inputs.melezh_version }}/melezh-${{ github.event.inputs.melezh_version }}-1.noarch_ru.rpm"

      - name: Log in to GHCR
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push English image (deb)
        run: |
          cd ./service/docker/ghcr/en-deb
          cp /tmp/melezh-build/en/oint.deb .
          cp /tmp/melezh-build/en/melezh.deb .
          docker build \
            -t ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-deb-en .
          docker push ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-deb-en

      - name: Build and Push Russian image (deb)
        run: |
          cd ./service/docker/ghcr/ru-deb
          cp /tmp/melezh-build/ru/oint.deb .
          cp /tmp/melezh-build/ru/melezh.deb .
          docker build \
            -t ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-deb-ru .
          docker push ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-deb-ru

      - name: Build and Push English image (rpm)
        run: |
          cd ./service/docker/ghcr/en-rpm
          cp /tmp/melezh-build/en/oint.rpm .
          cp /tmp/melezh-build/en/melezh.rpm .
          docker build \
            -t ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-rpm-ru .
          docker push ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-rpm-en

      - name: Build and Push Russian image (rpm)
        run: |
          cd ./service/docker/ghcr/ru-rpm
          cp /tmp/melezh-build/ru/oint.rpm .
          cp /tmp/melezh-build/ru/melezh.rpm .
          docker build \
            -t ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-rpm-ru .
          docker push ghcr.io/bayselonarrend/melezh:${{ github.event.inputs.version }}-rpm-ru